name: CI
on: push
#  pull_request:
#    branches:
#      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
          cd react-app
          npm ci
      - run: |
          cd react-app
          npm run format:check
      - run: |
          cd react-app
          npm test -- --coverage
        env:
          CI: true
