name: Test Action
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
          - foo
          - bar
          - baz
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.MULTILINE_FILE }} | base64 -d > file.txt
          cat file.txt
          md5sum file.txt
